# Generated by Django 4.1.6 on 2023-02-27 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_postlike'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='category_default.png', upload_to='category_pictures'),
        ),
    ]
