# Generated by Django 4.1.6 on 2023-03-03 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_category_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostCommentReply',
        ),
    ]
